version: "3"

services:
  postgres_db:
    container_name: auction_db
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: postgrespw
      POSTGRES_DB: carwiki
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - 5432:5432

  mongodb:
    image: mongo
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=mongopw
    ports:
      - 27017:27017
    volumes:
      - /var/lib/mongodb/data
    # networks:
    #   custom:
  rabbitmq:
    image: rabbitmq:3-management-alpine
    restart: always
    ports:
      - 5672:5672
      - 15672:15672
  # networks:
  #   custom:

volumes:
  pgdata:
