version: "2.2"

services:
  postgres_db:
    container_name: auction_db
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: postgrespw
      POSTGRES_DB: carwiki
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - 5432:5432

  mongodb:
    image: mongo
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=mongopw
    ports:
      - 27017:27017
    volumes:
      - mongodata:/var/lib/mongodb/data
 
  rabbitmq:
    image: rabbitmq:3-management-alpine
    restart: always
    ports:
      - 5672:5672
      - 15672:15672


  kong:
    image: kong:latest
    volumes:
      - ./kong.yml:/usr/local/kong/declarative/kong.yml
    environment:
      - KONG_DATABASE=off
      - KONG_DECLARATIVE_CONFIG=/usr/local/kong/declarative/kong.yml
      - KONG_PROXY_ACCESS_LOG=/dev/stdout
      - KONG_ADMIN_ACCESS_LOG=/dev/stdout
      - KONG_PROXY_ERROR_LOG=/dev/stderr
      - KONG_ADMIN_ERROR_LOG=/dev/stderr
      - KONG_ADMIN_LISTEN=0.0.0.0:8001, 0.0.0.0:8444 ssl
    ports:
      - "8000:8000"   
      - "127.0.0.1:8001:8001"
      - "127.0.0.1:8444:8444"
      - "8002:8002"
      - "8443:8443"
    extra_hosts:
      - "host.docker.internal=172.17.0.1"



volumes:
  pgdata:
  mongodata:

