spring.application.name=search-service
spring.data.mongodb.uri=${SPRING_DATA_MONGODB_URI:mongodb://carwiki:byiZf4TrWPs@localhost:27017/SearchDb?authSource=admin}
spring.data.mongodb.auto-index-creation=${SPRING_DATA_MONGODB_AUTO_INDEX_CREATION:true}
spring.redis.host=${SPRING_REDIS_HOST:localhost}
spring.redis.port=${SPRING_REDIS_PORT:6379}

springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.enabled=true
springdoc.api-docs.path=/api-docs


