spring.application.name=auction-service
spring.datasource.url=jdbc:mysql://localhost:3306/auction
spring.datasource.name=carwiki
spring.datasource.password=carwiki
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
server.port=8671
